In [5]:
import numpy as np

In [20]:
n=5
x=np.random.rand(n,2)
y=np.random.rand(n,2)

print(x)
print('\n')
print(y)


[[0.18114295 0.24013695]
 [0.70252554 0.40703712]
 [0.74798972 0.38878819]
 [0.99014075 0.04968415]
 [0.66696682 0.16796746]]


[[0.86666819 0.71940704]
 [0.04157076 0.97934161]
 [0.41313096 0.30949367]
 [0.99039659 0.49561373]
 [0.89730862 0.30390587]]


In [21]:
# евклидова
np.sqrt(np.square(x-y).sum(axis=1))

array([0.83644765, 0.87429608, 0.34411919, 0.44592966, 0.26746326])

In [22]:
# евклидова квадрат
np.square(x-y).sum(axis=1)

array([0.69964468, 0.76439364, 0.11841801, 0.19885326, 0.0715366 ])

In [23]:
# косинусная
(x*y).sum(axis=1) / ( np.linalg.norm(x,axis=1)*np.linalg.norm(y,axis=1) )

array([0.97327484, 0.53756805, 0.98664611, 0.91558087, 0.99681348])

In [24]:
# косинусная ненормированная
(x*y).sum(axis=1) 

array([0.32974705, 0.42783291, 0.42934519, 1.00525616, 0.64952138])

In [25]:
# манхэттенское расстояние
np.abs(x-y).sum(axis=1) 

array([1.16479533, 1.23325926, 0.41415329, 0.44618542, 0.36628021])

In [26]:
# чебышева
np.abs(x-y).max(axis=1) 

array([0.68552524, 0.66095478, 0.33485877, 0.44592958, 0.2303418 ])

In [27]:
# степенная
np.cbrt( np.power(x-y,5).sum(axis=1) )

array([-0.56113317,  0.40154884,  0.16151414, -0.2602818 , -0.08857218])