**извлечение признаков из текста на естественном языке**

частотный анализ TF-IDF

Евгений Борисов borisov.e@solarl.ru

## библиотеки

In [1]:
import numpy as np
np.set_printoptions(precision=2) # вывод на печать до 2 знака
import pandas as pd
import re

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
pd.options.display.max_colwidth = 200  

## тексты

In [4]:
docs = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
 ]

# docs = [
#     'После посадки в аэропорту Нью-Йорка воздушное судно отогнали в отдаленную часть аэропорта',
#     'У белой медведицы Джованны в зоопарке Мюнхена 21 ноября родился детеныш.',
#     'На юге столицы сотрудница полиции выжила после падения с седьмого этажа.',
#     ]

##  CountVectorizer + TF-IDF

In [5]:
cv = CountVectorizer()
cv.fit(docs)
cv_doc = cv.transform( docs )
cv_doc.todense()

matrix([[0, 1, 1, 1, 0, 0, 1, 0, 1],
        [0, 2, 0, 1, 0, 1, 1, 0, 1],
        [1, 0, 0, 1, 1, 0, 1, 1, 1],
        [0, 1, 1, 1, 0, 0, 1, 0, 1]])

In [6]:
tf = TfidfTransformer(use_idf=True, norm='l2',smooth_idf=True)
tf.fit( cv_doc )
tf.transform( cv_doc ).todense()

matrix([[0.  , 0.47, 0.58, 0.38, 0.  , 0.  , 0.38, 0.  , 0.38],
        [0.  , 0.69, 0.  , 0.28, 0.  , 0.54, 0.28, 0.  , 0.28],
        [0.51, 0.  , 0.  , 0.27, 0.51, 0.  , 0.27, 0.51, 0.27],
        [0.  , 0.47, 0.58, 0.38, 0.  , 0.  , 0.38, 0.  , 0.38]])

### TfidfVectorizer

In [7]:
# TfidfVectorizer = CountVectorizer + TfidfTransformer

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
tf.fit( docs )
tf.transform( docs ).todense()

matrix([[0.  , 0.47, 0.58, 0.38, 0.  , 0.  , 0.38, 0.  , 0.38],
        [0.  , 0.69, 0.  , 0.28, 0.  , 0.54, 0.28, 0.  , 0.28],
        [0.51, 0.  , 0.  , 0.27, 0.51, 0.  , 0.27, 0.51, 0.27],
        [0.  , 0.47, 0.58, 0.38, 0.  , 0.  , 0.38, 0.  , 0.38]])

##  HashingVectorizer + TF-IDF

In [9]:
hv = HashingVectorizer(n_features=2**3)
hv.fit(docs)
hv_doc = hv.transform( docs )
hv_doc.todense()

matrix([[-0.89,  0.  ,  0.  ,  0.  ,  0.  ,  0.45,  0.  ,  0.  ],
        [-0.82,  0.  ,  0.  ,  0.41,  0.  ,  0.41,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  , -0.71,  0.71,  0.  ,  0.  ],
        [-0.89,  0.  ,  0.  ,  0.  ,  0.  ,  0.45,  0.  ,  0.  ]])

In [10]:
tf = TfidfTransformer( use_idf=False )
tf.fit( hv_doc )
tf.transform( hv_doc ).todense()

matrix([[-0.89,  0.  ,  0.  ,  0.  ,  0.  ,  0.45,  0.  ,  0.  ],
        [-0.82,  0.  ,  0.  ,  0.41,  0.  ,  0.41,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  , -0.71,  0.71,  0.  ,  0.  ],
        [-0.89,  0.  ,  0.  ,  0.  ,  0.  ,  0.45,  0.  ,  0.  ]])

---

In [ ]:
# Sebastian Raschka   Python Machine Learning  - Packt Publishing Ltd, 2015