**сеть Хемминга**

нечёткий поиск

Евгений Борисов esborisov@sevsu.ru

---

А.Арустамов, А.Стариков    Ассоциативная память.Применение сетей Хемминга для нечеткого поиска.    
https://basegroup.ru/community/articles/assoc

## библиотеки

In [1]:
import numpy as np
# import matplotlib.pyplot as plt
# import imageio
# import pickle
# import gzip

##  загружаем данные 

In [2]:
def read_list_txt(fname):
    with open(fname,'rt') as f: 
        return [ w.strip() for w in f.read().split('\n') if w.strip() ]
        
ideal = read_list_txt('../data/towns/ideal_u.txt')
test = read_list_txt('../data/towns/test_u.txt')
   
len(ideal), len(test)

(112, 112)

In [3]:
max([len(w) for w in ideal]), max([len(w) for w in test]), 

(14, 14)

In [8]:
# Кодирование строится таким образом, 
# что бы стоящие рядом на компьютерной клавиатуре символы 
# имели близкие по Хеммингу коды.
# Таким образом должно достигаться наиболее эффективное исправление опечаток.


CODE_A = {
   'к':(0,0,0,0,0,),
   'ж':(0,0,0,0,1,),
   'г':(0,0,0,1,0,),
   'щ':(0,0,0,1,1,),
   'ч':(0,0,1,0,0,),
   'х':(0,0,1,0,1,),
   'ю':(0,0,1,1,0,),
   'с':(0,0,1,1,1,),
   'у':(0,1,0,0,0,),
   'б':(0,1,0,0,1,),
   'л':(0,1,0,1,0,),
   'е':(0,1,0,1,1,),
   'о':(0,1,1,0,0,),
   'р':(0,1,1,0,1,),
   'н':(0,1,1,1,0,),
   'й':(0,1,1,1,1,),
   'т':(1,0,0,0,0,),
   'з':(1,0,0,0,1,),
   'ы':(1,0,0,1,0,),
   'п':(1,0,0,1,1,),
   'ф':(1,0,1,0,0,),
   'ш':(1,0,1,0,1,),
   'м':(1,0,1,1,0,),
   'э':(1,0,1,1,1,),
   'ъ':(1,1,0,0,0,),
   'д':(1,1,0,0,1,),
   'в':(1,1,0,1,0,),
   'а':(1,1,0,1,1,),
   'ц':(1,1,1,0,0,),
   'и':(1,1,1,0,1,),
   'я':(1,1,1,1,0,),
   'ь':(1,1,1,1,1,)
}

# CODE_A = {
#    'к':(-1,-1,-1,-1,-1,),
#    'ж':(-1,-1,-1,-1, 1,),
#    'г':(-1,-1,-1, 1,-1,),
#    'щ':(-1,-1,-1, 1, 1,),
#    'ч':(-1,-1, 1,-1,-1,),
#    'х':(-1,-1, 1,-1, 1,),
#    'ю':(-1,-1, 1, 1,-1,),
#    'с':(-1,-1, 1, 1, 1,),
#    'у':(-1, 1,-1,-1,-1,),
#    'б':(-1, 1,-1,-1, 1,),
#    'л':(-1, 1,-1, 1,-1,),
#    'е':(-1, 1,-1, 1, 1,),
#    'о':(-1, 1, 1,-1,-1,),
#    'р':(-1, 1, 1,-1, 1,),
#    'н':(-1, 1, 1, 1,-1,),
#    'й':(-1, 1, 1, 1, 1,),
#    'т':( 1,-1,-1,-1,-1,),
#    'з':( 1,-1,-1,-1, 1,),
#    'ы':( 1,-1,-1, 1,-1,),
#    'п':( 1,-1,-1, 1, 1,),
#    'ф':( 1,-1, 1,-1,-1,),
#    'ш':( 1,-1, 1,-1, 1,),
#    'м':( 1,-1, 1, 1,-1,),
#    'э':( 1,-1, 1, 1, 1,),
#    'ъ':( 1, 1,-1,-1,-1,),
#    'д':( 1, 1,-1,-1, 1,),
#    'в':( 1, 1,-1, 1,-1,),
#    'а':( 1, 1,-1, 1, 1,),
#    'ц':( 1, 1, 1,-1,-1,),
#    'и':( 1, 1, 1,-1, 1,),
#    'я':( 1, 1, 1, 1,-1,),
#    'ь':( 1, 1, 1, 1, 1,),
# }


CODE_V = { CODE_A[a]:a for a in CODE_A }

def encode(w): return  [ CODE_A[a] for a in list(w.lower()) ]
def decode(c): return  [ CODE_V[v] for v in c ]

In [9]:
# ideal_c = [ encode(w) for w in ideal ]
# [ ''.join(decode(w)) for w in ideal_c ]

In [11]:
max_word_len = max([len(w) for w in ideal])*2
z = np.zeros(max_word_len)

x = [ np.hstack( encode(w)) for w in ideal ]
x = [ v  z for v in x ]


[array([1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
        0, 1, 0, 1, 1, 0, 1, 1]),
 array([1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
        0, 0, 0]),
 array([1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
        0, 0, 0, 1, 0, 0, 1, 0]),
 array([1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
        0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
        1]),
 array([1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
        0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1]),
 array([0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
        0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0]),
 array([0, 1, 0, 0, 1, 

![neural-net-hamming](http://mechanoid.su/content/neural-net-hamming-classifier.html/nnet.png)

In [6]:
code_len = len(CODE_A['а']) # длинна кода символа
voc_len = len(ideal) # размер словаря
max_word_len = max([len(w) for w in ideal])

size_layer_0 = code_len * (max_word_len*2) # размер входого слоя, (кодированное слово)
size_layer_1 = voc_len # # размер выходого слоя (индикатор позиции в словаре)

## загружаем память сети

In [ ]:
# масштабруем в [-1,+1]
X_train = np.vstack([ (m.flatten()>0)*2-1 for m in ideal ])

In [ ]:
m = X_train.shape[0] # количество учебных примеров 
c=1.0/(2.0*m) # коэффициент торможения

W1 = (0.5*X_train).T # веса для нейронов первого слоя
W2 = -(np.ones(m)-np.eye(m))*c+np.eye(m) # веса для нейронов второго слоя

In [ ]:
def run(x,W1,W2,max_iter=50):
    o = x.dot(W1)
    for i in range(max_iter):
        o_prev=o.copy() # сохраняем состояние
        o = np.max( [ o.dot(W2), np.zeros(m) ], axis=0 ) # переходим в новое состояние
        # если состояние не изменилось то завершаем
        if np.all(o==o_prev): break
    # print(i)  
    return o        

## тестируем

In [ ]:
def make_test(tt,figsize=(20,2)):
    # масштабруем в [-1,+1]
    X_test = np.vstack([(m.flatten()>0)*2-1 for m in tt])

    # выполняем для всех тестовых примеров
    out = [ np.argmax(run(X_test[i,:],W1,W2)) for i in range(X_test.shape[0]) ]

    f,axarr = plt.subplots(2,len(tt),sharey=False,sharex=False,figsize=figsize)
    for i in range(len(tt)):
        axarr[0,i].imshow( tt[i] )
        axarr[0,i].axis('off')
        axarr[1,i].imshow( ideal[out[i]])
        axarr[1,i].axis('off')


---

In [ ]:
# мало зашумлённые
make_test(test[3],figsize=(14,4))